services:

  jupyter:

    build:
      context: .
      dockerfile: jupyter/Dockerfile


    ports:
      - "8888:8888"


    volumes:

      - ./models:/models

      - ./Data_Files:/Data_Files

      - ./jupyter:/workspace



  api:


    build:

      context: .

      dockerfile: api/Dockerfile


    ports:

      - "8000:8000"


    volumes:

      - ./models:/models


    restart: always
